version: "3.7"

networks:
    laravel:

services:
    nginx:
        image: nginx:stable-alpine
        container_name: nginx_laravel
        ports:
            -   "8088:80"
        volumes:
            -   ./voting-app-local:/var/www/html
            -   ./nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - php
            - mysql
        networks:
            - laravel
    mysql:
        image: mysql:5.7.22
        container_name: mysql_laravel
        restart: unless-stopped
        tty: true
        ports:
            -   "3306:3306"
        volumes:
            - ./mysql:/var/lib/mysql
        environment:
            MYSQL_DATABASE: voting
            MYSQL_USER: root
            MYSQL_PASSWORD: secret
            MYSQL_ROOT_PASSWORD: secret
            SERVICE_TAGS: dev
            SERVICE_NAME: mysql
        networks:
            - laravel
    php:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: php_laravel
        volumes:
            - ./voting-app-local:/var/www/html
        ports:
            - "9000:9000"
        networks:
            - laravel

    phpmyadmin:
        container_name: phpmyadmin_laravel
        image: phpmyadmin
        restart: always
        ports:
            - 8899:80
        environment:
            - PMA_ARBITRARY=1
        networks:
            - laravel
    elasticsearch:
        image: elasticsearch:8.2.2
        container_name: elasticsearch
        restart: always
        ports:
            - '9200:9200'
        environment:
            - discovery.type=single-node
            - xpack.security.enabled=false
        ulimits:
            memlock:
                soft: -1
                hard: -1
            nofile:
                soft: 65536
                hard: 65536
        volumes:
            -   elasticsearch-volume:/usr/share/elasticsearch/data
    kibana:
        image: kibana:8.2.2
        restart: always
        ports:
            - '5601:5601'
        environment:
            - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
        depends_on:
            -   elasticsearch
volumes:
    elasticsearch-volume:
        driver: local